web:
  image: nginx:latest
  ports:
    - "8080:8080"
  volumes:
    - nginx.template:/etc/nginx/conf.d/nginx.template
    - clients/web/:/html/
  links:
    - api
  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

api:
  build: .
  volumes:
    - .:/app/
  links:
    - db

db:
  image: mongo:3.2
  volumes:
    - volumes/db:/data/db
